name: pynsource
version: git
summary: 'Pynsource - reverse engineer Python source code into UML'
description: "This is my-snap's description. You have a paragraph or two to tell the\nmost important story about your snap. Keep it under 100 words though,\nwe live in tweetspace and your description wants to look good in the snap\nstore.\n"
grade: devel
confinement: strict
base: core18
apps:
  pynsource:
    command: 'desktop-launch python3 $SNAP/usr/bin/pynsource-gui.py'
    plugs:
      - x11
      - unity7
      - pulseaudio
      - home
      - gsettings
      - network
parts:
  desktop-gtk3:
    build-packages:
      - build-essential
      - libgtk-3-dev
    make-parameters:
      - FLAVOR=gtk3
    plugin: make
    source: 'https://github.com/ubuntu/snapcraft-desktop-helpers.git'
    source-subdir: gtk
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5
      - fcitx-frontend-gtk3
  pynsource:
    plugin: python
    python-version: python3
    source: ./src
    stage-packages:
      - libssl-dev
      - libjpeg-dev
      - libtiff-dev
      - libsdl1.2-dev
      - libnotify-dev
      - freeglut3
      - ibus-gtk3
      - libwebkitgtk-3.0-0
      - zlib1g
      - libsm6
      - libpulse0
      - libslang2
    python-packages:
      - 'https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/wxPython-4.0.4-cp36-cp36m-linux_x86_64.whl'
    requirements:
        - /root/project/requirements-linux.txt
    override-build: "snapcraftctl build\ncp $SNAPCRAFT_PART_SRC/pynsource-gui.py $SNAPCRAFT_PART_INSTALL/usr/bin/\nchmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/pynsource-gui.py\n"

